# $NetBSD: Makefile.linux,v 1.1 2016/06/08 01:16:35 christos Exp $
SRCS=mopcopy.c
OBJS=${SRCS:.c=.o}

LDLIBS+=../common/libcommon.a
CFLAGS+=-I../common
# -DNOAOUT not needed as long as including of files from netbsd_h works

mopcopy: ${OBJS}

clean:
	rm -f ${OBJS} mopcopy
